interface Env {
  DB: D1Database
  GITHUB_OWNER: string
  GITHUB_REPO: string
  GITHUB_DEFAULT_BRANCH: string
  PAGES_URL: string
  GITHUB_CLIENT_ID: string
  GITHUB_CLIENT_SECRET: string
  SESSION_ENCRYPTION_KEY: string
}

type Session = { userId: string; login: string; token: string }
const json = (data: unknown, status = 200, origin = '*') => new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'access-control-allow-origin': origin, 'access-control-allow-credentials': 'true', 'access-control-allow-headers': 'content-type', 'access-control-allow-methods': 'GET,POST,OPTIONS' } })
const now = () => Math.floor(Date.now() / 1000)
const encode = (value: ArrayBuffer | Uint8Array) => btoa(String.fromCharCode(...new Uint8Array(value instanceof ArrayBuffer ? value : value.buffer)))
const decode = (value: string) => Uint8Array.from(atob(value), (char) => char.charCodeAt(0))
async function hash(value: string) { const bytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)); return encode(bytes) }
async function key(env: Env) { return crypto.subtle.importKey('raw', new TextEncoder().encode(env.SESSION_ENCRYPTION_KEY.padEnd(32, '0').slice(0, 32)), 'AES-GCM', false, ['encrypt', 'decrypt']) }
async function encrypt(value: string, env: Env) { const iv = crypto.getRandomValues(new Uint8Array(12)); const encrypted = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, await key(env), new TextEncoder().encode(value)); return `${encode(iv)}.${encode(encrypted)}` }
async function decrypt(value: string, env: Env) { const [iv, body] = value.split('.'); const decrypted = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: decode(iv) }, await key(env), decode(body)); return new TextDecoder().decode(decrypted) }
function cookie(request: Request, name: string) { return request.headers.get('Cookie')?.split(';').map((part) => part.trim()).find((part) => part.startsWith(`${name}=`))?.slice(name.length + 1) }
async function session(request: Request, env: Env): Promise<Session | null> { const raw = cookie(request, 'scp_session'); if (!raw) return null; const sessionHash = await hash(raw); const row = await env.DB.prepare('SELECT * FROM auth_sessions WHERE session_hash = ? AND expires_at > ?').bind(sessionHash, now()).first<{ github_user_id: string; github_login: string; access_token_ciphertext: string }>(); if (!row) return null; return { userId: row.github_user_id, login: row.github_login, token: await decrypt(row.access_token_ciphertext, env) } }
async function github(env: Env, token: string, endpoint: string, init: RequestInit = {}) { const response = await fetch(`https://api.github.com${endpoint}`, { ...init, headers: { accept: 'application/vnd.github+json', authorization: `Bearer ${token}`, 'x-github-api-version': '2022-11-28', ...(init.headers ?? {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message ?? `GitHub API ${response.status}`); return body }
function safeId(value: string) { return value.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '').slice(0, 70) }
function b64(value: string) { return btoa(unescape(encodeURIComponent(value))) }
const archiveRequired = ['id', 'itemNumber', 'title', 'objectClass', 'threatLevel', 'status', 'site', 'clearanceLevel', 'lastUpdated', 'image', 'imageCaption', 'containmentProcedures', 'description', 'discoveryLog', 'appendices', 'characteristics', 'radarMetrics', 'relatedArchives']
const archiveAllowed = new Set([...archiveRequired, 'archiveStatus', 'metadata'])
const isRecord = (value: unknown): value is Record<string, unknown> => value !== null && typeof value === 'object' && !Array.isArray(value)
const checkString = (value: unknown, name: string, min = 1, max = Infinity) => typeof value === 'string' && value.length >= min && value.length <= max ? null : `${name} must be a string with ${min}-${max} characters`
function validateArchive(value: Record<string, unknown>) {
  const errors: string[] = []
  for (const field of archiveRequired) if (!(field in value)) errors.push(`missing ${field}`)
  for (const field of Object.keys(value)) if (!archiveAllowed.has(field)) errors.push(`unknown field ${field}`)
  for (const [field, min, max] of [['id', 1, 80], ['itemNumber', 1, 80], ['title', 1, 120], ['objectClass', 1, 40], ['threatLevel', 1, 40], ['status', 1, 80], ['site', 1, 120], ['clearanceLevel', 1, 40], ['lastUpdated', 1, 40], ['image', 0, Infinity], ['imageCaption', 0, 500] ] as const) { const error = checkString(value[field], field, min, max); if (error) errors.push(error) }
  if (typeof value.id === 'string' && !/^[a-z0-9-]{3,80}$/.test(value.id)) errors.push('id has invalid format')
  for (const field of ['containmentProcedures', 'description', 'discoveryLog']) { const section = value[field]; if (!isRecord(section)) { errors.push(`${field} must be an object`); continue }; const titleError = checkString(section.title, `${field}.title`, 1, 100); if (titleError) errors.push(titleError); if (!Array.isArray(section.paragraphs) || section.paragraphs.length < 1 || section.paragraphs.length > 30) errors.push(`${field}.paragraphs must contain 1-30 items`); else section.paragraphs.forEach((item, index) => { const error = checkString(item, `${field}.paragraphs[${index}]`, 1, 5000); if (error) errors.push(error) }) }
  if (!Array.isArray(value.appendices) || value.appendices.length > 20) errors.push('appendices must contain at most 20 items')
  if (!Array.isArray(value.characteristics) || value.characteristics.length > 12) errors.push('characteristics must contain at most 12 items')
  if (!Array.isArray(value.radarMetrics) || value.radarMetrics.length !== 6) errors.push('radarMetrics must contain exactly 6 items')
  else value.radarMetrics.forEach((item, index) => { if (!isRecord(item)) { errors.push(`radarMetrics[${index}] must be an object`); return }; const labelError = checkString(item.label, `radarMetrics[${index}].label`, 1, 60); if (labelError) errors.push(labelError); if (typeof item.value !== 'number' || item.value < 0 || item.value > 100) errors.push(`radarMetrics[${index}].value must be 0-100`) })
  if (!Array.isArray(value.relatedArchives) || value.relatedArchives.length > 20) errors.push('relatedArchives must contain at most 20 items')
  if (value.archiveStatus !== undefined && !['draft', 'published'].includes(String(value.archiveStatus))) errors.push('archiveStatus is invalid')
  return errors
}
async function createSubmission(request: Request, env: Env, origin: string) {
  const current = await session(request, env); if (!current) return json({ error: '请先使用 GitHub 登录。' }, 401, origin)
  const payload = await request.json<{ archive?: Record<string, unknown>; image?: { filename: string; contentBase64: string; mimeType: string } }>()
  const archive = payload.archive; if (!archive || !isRecord(archive)) return json({ error: '档案数据不完整。' }, 400, origin)
  const archiveErrors = validateArchive(archive); if (archiveErrors.length) return json({ error: '档案数据校验失败。', details: archiveErrors }, 400, origin)
  const id = safeId(String(archive.id)); if (!id || id !== archive.id) return json({ error: '档案 slug 只允许小写字母、数字和短横线。' }, 400, origin)
  const image = payload.image; if (!image || !['image/png', 'image/jpeg', 'image/webp'].includes(image.mimeType) || image.contentBase64.length > 7_000_000) return json({ error: '图片格式或大小不符合要求。' }, 400, origin)
  const existing = await github(env, current.token, `/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/contents/content/archives/${id}.json?ref=${env.GITHUB_DEFAULT_BRANCH}`, {} ).catch(() => null); if (existing) return json({ error: '该档案 slug 已存在，请换一个。' }, 409, origin)
  const branch = `contrib/archive-${id}-${current.userId.slice(-8)}`; const base = await github(env, current.token, `/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/git/ref/heads/${env.GITHUB_DEFAULT_BRANCH}`); await github(env, current.token, `/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/git/refs`, { method: 'POST', body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: base.object.sha }) });
  const archiveContent = `${JSON.stringify({ ...archive, archiveStatus: 'draft', metadata: { authorGithubLogin: current.login, submittedAt: new Date().toISOString() } }, null, 2)}\n`; const root = `/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/contents`;
  await github(env, current.token, `${root}/content/archives/${id}.json`, { method: 'PUT', body: JSON.stringify({ message: `Add archive: ${archive.itemNumber} / ${archive.title}`, content: b64(archiveContent), branch }) });
  const extension = image.mimeType === 'image/png' ? 'png' : image.mimeType === 'image/webp' ? 'webp' : 'jpg'; const imagePath = `content/assets/${id}.${extension}`; await github(env, current.token, `${root}/${imagePath}`, { method: 'PUT', body: JSON.stringify({ message: `Add asset: ${archive.itemNumber}`, content: image.contentBase64, branch }) });
  const pr = await github(env, current.token, `/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/pulls`, { method: 'POST', body: JSON.stringify({ title: `Add archive: ${archive.itemNumber} / ${archive.title}`, head: branch, base: env.GITHUB_DEFAULT_BRANCH, body: `## 档案贡献\n\n- 项目：${archive.itemNumber}\n- 标题：${archive.title}\n- 提交者：@${current.login}\n\n该 PR 由 SCP 档案站在线编辑器创建，请维护者审核内容后合并。` }) });
  const idValue = crypto.randomUUID(); const timestamp = now(); await env.DB.prepare('INSERT INTO submissions (id, github_user_id, github_login, archive_id, branch_name, pull_request_number, pull_request_url, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').bind(idValue, current.userId, current.login, id, branch, pr.number, pr.html_url, 'open', timestamp, timestamp).run(); await env.DB.prepare('INSERT INTO audit_events (event_type, github_login, submission_id, result, created_at) VALUES (?, ?, ?, ?, ?)').bind('submission.created', current.login, idValue, 'success', timestamp).run(); return json({ id: idValue, status: 'open', pullRequestNumber: pr.number, pullRequestUrl: pr.html_url, archiveId: id, createdAt: new Date(timestamp * 1000).toISOString() }, 201, origin)
}
export default { async fetch(request: Request, env: Env): Promise<Response> { const origin = env.PAGES_URL.replace(/\/$/, ''); if (request.method === 'OPTIONS') return json({}, 204, origin); const url = new URL(request.url); try {
  if (url.pathname === '/auth/github') { const state = crypto.randomUUID(); await env.DB.prepare('INSERT INTO oauth_states (state_hash, redirect_uri, expires_at) VALUES (?, ?, ?)').bind(await hash(state), `${env.PAGES_URL}?view=editor`, now() + 600).run(); const callback = `${url.origin}/auth/callback`; return Response.redirect(`https://github.com/login/oauth/authorize?client_id=${encodeURIComponent(env.GITHUB_CLIENT_ID)}&redirect_uri=${encodeURIComponent(callback)}&scope=read:user%20user:email%20public_repo&state=${encodeURIComponent(state)}`, 302) }
  if (url.pathname === '/auth/callback') { const code = url.searchParams.get('code'); const state = url.searchParams.get('state'); if (!code || !state) return new Response('OAuth 参数不完整。', { status: 400 }); const stateRow = await env.DB.prepare('SELECT * FROM oauth_states WHERE state_hash = ? AND expires_at > ?').bind(await hash(state), now()).first<{ redirect_uri: string }>(); if (!stateRow) return new Response('OAuth state 无效或已过期。', { status: 400 }); const tokenResponse = await fetch('https://github.com/login/oauth/access_token', { method: 'POST', headers: { accept: 'application/json', 'content-type': 'application/json' }, body: JSON.stringify({ client_id: env.GITHUB_CLIENT_ID, client_secret: env.GITHUB_CLIENT_SECRET, code }) }); const tokenBody = await tokenResponse.json<{ access_token?: string }>(); if (!tokenBody.access_token) return new Response('GitHub OAuth 失败。', { status: 502 }); const profile = await github(env, tokenBody.access_token, '/user'); const rawSession = crypto.randomUUID(); await env.DB.prepare('INSERT INTO auth_sessions (session_hash, github_user_id, github_login, access_token_ciphertext, created_at, expires_at) VALUES (?, ?, ?, ?, ?, ?)').bind(await hash(rawSession), String(profile.id), profile.login, await encrypt(tokenBody.access_token, env), now(), now() + 60 * 60 * 24 * 14).run(); return new Response(null, { status: 302, headers: { location: stateRow.redirect_uri, 'set-cookie': `scp_session=${rawSession}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=1209600` } }) }
  if (url.pathname === '/auth/logout' && request.method === 'POST') { const raw = cookie(request, 'scp_session'); if (raw) await env.DB.prepare('DELETE FROM auth_sessions WHERE session_hash = ?').bind(await hash(raw)).run(); return new Response(null, { status: 204, headers: { 'set-cookie': 'scp_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0', 'access-control-allow-origin': origin, 'access-control-allow-credentials': 'true' } }) }
  if (url.pathname === '/api/me') { const current = await session(request, env); return json({ user: current ? { id: current.userId, login: current.login } : null }, 200, origin) }
  if (url.pathname === '/api/submissions' && request.method === 'POST') return createSubmission(request, env, origin)
  const match = url.pathname.match(/^\/api\/submissions\/([^/]+)$/); if (match && request.method === 'GET') { const current = await session(request, env); if (!current) return json({ error: '未登录。' }, 401, origin); const row = await env.DB.prepare('SELECT * FROM submissions WHERE id = ? AND github_user_id = ?').bind(match[1], current.userId).first(); return row ? json(row, 200, origin) : json({ error: '提交不存在。' }, 404, origin) }
  return json({ error: 'Not found' }, 404, origin)
 } catch (error) { return json({ error: error instanceof Error ? error.message : '服务器错误' }, 500, origin) } } }
