name = "scp-archive-contributor-api"
main = "src/index.ts"
compatibility_date = "2026-07-12"

[[d1_databases]]
binding = "DB"
database_name = "scp-archive-contributor"
database_id = "1ac1e99c-0099-481d-b71d-0c66c724da50"

[vars]
GITHUB_OWNER = "lantean600"
GITHUB_REPO = "scp-archive-terminal"
GITHUB_DEFAULT_BRANCH = "main"
PAGES_URL = "https://lantean600.github.io/scp-archive-terminal/"
